package com.gradecalculator.dto.response;

public record EnrollmentResponse(
        Long id,
        Long studentId,
        String studentName,
        String studentRollNumber,
        Long courseId,
        String courseCode,
        String courseName,
        Integer credits,
        String courseType,
        Long semesterId,
        Integer semesterNumber,
        String grade,
        int gradePoints,
        int creditPoints,
        Integer cieMarks,
        Integer cieTheoryMarks,
        Integer cieLabMarks,
        Integer test1Marks,
        Integer test2Marks,
        Integer assignmentMarks,
        Integer oaaMarks,
        Integer regularLabMarks,
        Integer labTestMarks,
        Integer labRecordMarks,
        Integer seeMarks,
        Integer graceMarks,
        Integer totalMarks) {
}
