package com.gradecalculator.service;

import com.gradecalculator.model.Enrollment;
import com.gradecalculator.model.Student;
import com.gradecalculator.repository.EnrollmentRepository;
import com.gradecalculator.repository.StudentRepository;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.util.List;

/**
 * PDF Transcript Generation Service
 */
@Service
public class TranscriptPdfService {

    private final EnrollmentRepository enrollmentRepository;
    private final StudentRepository studentRepository;

    public TranscriptPdfService(EnrollmentRepository enrollmentRepository, StudentRepository studentRepository) {
        this.enrollmentRepository = enrollmentRepository;
        this.studentRepository = studentRepository;
    }

    /**
     * Generate PDF transcript for a student
     */
    public byte[] generateTranscript(Long studentId) throws Exception {
        Student student = studentRepository.findById(studentId)
                .orElseThrow(() -> new IllegalArgumentException("Student not found"));

        List<Enrollment> enrollments = enrollmentRepository.findByStudentId(studentId);

        Document document = new Document(PageSize.A4);
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfWriter.getInstance(document, baos);

        document.open();

        // Header
        Font headerFont = new Font(Font.HELVETICA, 18, Font.BOLD, new Color(139, 21, 56));
        Font subHeaderFont = new Font(Font.HELVETICA, 12, Font.BOLD, Color.GRAY);

        Paragraph title = new Paragraph("ACADEMIC TRANSCRIPT", headerFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        document.add(new Paragraph(" "));

        // Student Info
        PdfPTable infoTable = new PdfPTable(2);
        infoTable.setWidthPercentage(100);
        
        addTableRow(infoTable, "Student Name:", student.getName());
        addTableRow(infoTable, "Roll Number:", student.getStudentId());
        
        document.add(infoTable);
        document.add(new Paragraph(" "));

        // Grades Table
        PdfPTable gradesTable = new PdfPTable(5);
        gradesTable.setWidthPercentage(100);
        gradesTable.setWidths(new float[]{2f, 3f, 1f, 1f, 1f});

        // Headers
        addTableHeader(gradesTable, "Course Code");
        addTableHeader(gradesTable, "Course Name");
        addTableHeader(gradesTable, "Credits");
        addTableHeader(gradesTable, "Grade");
        addTableHeader(gradesTable, "Points");

        // Data
        for (Enrollment e : enrollments) {
            gradesTable.addCell(e.getCourse().getCourseCode());
            gradesTable.addCell(e.getCourse().getCourseName());
            gradesTable.addCell(String.valueOf(e.getCourse().getCredits()));
            gradesTable.addCell(e.getGrade() != null ? e.getGrade().getGrade() : "-");
            gradesTable.addCell(String.valueOf(e.getCreditPoints()));
        }

        document.add(gradesTable);

        // Footer
        document.add(new Paragraph(" "));
        Paragraph footer = new Paragraph("Generated by GradePoint", subHeaderFont);
        footer.setAlignment(Element.ALIGN_RIGHT);
        document.add(footer);

        document.close();
        return baos.toByteArray();
    }

    private void addTableRow(PdfPTable table, String label, String value) {
        Font bold = new Font(Font.HELVETICA, 10, Font.BOLD);
        Font normal = new Font(Font.HELVETICA, 10);
        table.addCell(new PdfPCell(new Phrase(label, bold)));
        table.addCell(new PdfPCell(new Phrase(value, normal)));
    }

    private void addTableHeader(PdfPTable table, String text) {
        Font font = new Font(Font.HELVETICA, 9, Font.BOLD, Color.WHITE);
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(new Color(139, 21, 56));
        cell.setPaddingBottom(5);
        table.addCell(cell);
    }
}